spring:
  application:
    name: simpeg-api
  data:
    mongodb:
      uri:
server:
  port :
  error:
    include-stacktrace: never
    include-message: always

logging:
  level:
    '[id.ac.arraniry.simpegapi]': trace
  file:
    path: /var/tmp
env:
  data:
    simpeg-graphql-url: ""
    secret-key: ""
    cdn-host: ""
    cdn-home-folder: ""
    cdn-username: ""
    cdn-password: ""
    cdn-usul-izin-folder: ""